portal-impl.jar=com.liferay.portal:com.liferay.portal.impl:3.26.3
portal-service.jar=com.liferay.portal:com.liferay.portal.kernel:3.46.1
spring-aop.jar=org.springframework:spring-aop:4.3.22.RELEASE
spring-asm.jar=__remove__
spring-beans.jar=org.springframework:spring-beans:4.3.22.RELEASE
spring-core.jar=org.springframework:spring-core:4.3.22.RELEASE
spring-context.jar=org.springframework:spring-context:4.3.22.RELEASE
spring-context-support.jar=org.springframework:spring-context-support:4.3.22.RELEASE
spring-expression.jar=org.springframework:spring-expression:4.3.22.RELEASE
spring-web.jar=org.springframework:spring-web:4.3.22.RELEASE
spring-web-portlet.jar=org.springframework:spring-webmvc-portlet:4.3.22.RELEASE
spring-webmvc.jar=org.springframework:spring-webmvc:4.3.22.RELEASE
spring-webmvc-portlet.jar=org.springframework:spring-webmvc-portlet:4.3.22.RELEASE
util-bridges.jar=com.liferay.portal:com.liferay.util.bridges:5.0.1
util-java.jar=com.liferay.portal:com.liferay.util.java:3.0.24
util-taglib.jar=com.liferay.portal:com.liferay.util.taglib:3.4.2